// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonaFlyUI.Server.Infrastructure.Data;

#nullable disable

namespace SonaFlyUI.Server.Migrations
{
    [DbContext(typeof(SonaFlyDbContext))]
    [Migration("20260917013321_AddCatalogReleaseAndOverrides")]
    partial class AddCatalogReleaseAndOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumArtistId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtworkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumArtistId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("Title");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtworkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.ArtworkAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceTrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("ArtworkAssets");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Auditorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Auditoriums");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.AuditoriumQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QueuedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueuedByUserId");

                    b.HasIndex("TrackId");

                    b.HasIndex("AuditoriumId", "Position");

                    b.ToTable("AuditoriumQueueItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AcousticFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintDigest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileRevisionId");

                    b.HasIndex("FingerprintDigest");

                    b.ToTable("AcousticFingerprints");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "GroupKey");

                    b.ToTable("AlbumGroups");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProposedDisc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProposedPosition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TrackId");

                    b.ToTable("AlbumGroupMembers");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.CatalogOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApprovedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFingerprintDigest")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ValueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueText")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Field")
                        .IsUnique();

                    b.ToTable("CatalogOverrides");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.CatalogRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceProposalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MusicBrainzReleaseId");

                    b.ToTable("CatalogReleases");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.ChangeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewSha256")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewTagSnapshotJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldSha256")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldTagSnapshotJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsAttemptedJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsCompletedJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.HasIndex("TrackId");

                    b.ToTable("ChangeJournals");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Retryable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subsystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("IdentificationErrors");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmbiguousCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientRequestKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("FingerprintedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckpoint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiryUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LookedUpCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposalsReadyCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolvedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestKey")
                        .IsUnique();

                    b.HasIndex("LibraryRootId", "Status");

                    b.ToTable("IdentificationJobs");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiryUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Retryable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryUtc");

                    b.HasIndex("TrackId");

                    b.HasIndex("JobId", "Status");

                    b.ToTable("IdentificationWorkItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.MetadataProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceSnapshotJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedModifiedUtcSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldMask")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewAlbum")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewArtist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewDiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewTrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NewYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldAlbum")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldArtist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OldDiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OldTrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OldYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecordingCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReleaseCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Status");

                    b.HasIndex("TrackId", "Status");

                    b.ToTable("MetadataProposals");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.OriginalTagSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FileRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDate")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isrc")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFieldsJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileRevisionId")
                        .IsUnique();

                    b.ToTable("OriginalTagSnapshots");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.ProviderCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKeyDigest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryShape")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "CacheKeyDigest", "QueryShape")
                        .IsUnique();

                    b.ToTable("ProviderCacheEntries");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.RecordingCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcoustId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfidenceBand")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conflicts")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RawProviderScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoringBreakdownJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MusicBrainzRecordingId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("RecordingCandidates");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.ReleaseCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbiguitySetId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAmbiguityMember")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoringBreakdownJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MusicBrainzReleaseId");

                    b.ToTable("ReleaseCandidates");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.TrackFileRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtcSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Sha256CalculatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("TrackId");

                    b.HasIndex("LibraryRootId", "NormalizedPath");

                    b.ToTable("TrackFileRevisions");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.LibraryRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastScanError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastScanStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryRoots");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.MixedTape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("MixedTapes");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.MixedTapeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MixedTapeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MixedTapeId");

                    b.HasIndex("TrackId");

                    b.ToTable("MixedTapeItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemPlaylist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesMissing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUnverified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRootId");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitRateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CatalogReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtcSource")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CatalogReleaseId");

                    b.HasIndex("FilePath");

                    b.HasIndex("LibraryRootId");

                    b.HasIndex("PrimaryArtistId");

                    b.HasIndex("Title");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TrackGenres");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.UserRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestrictionType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RestrictionType", "TargetId")
                        .IsUnique();

                    b.ToTable("UserRestrictions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Album", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Artist", "AlbumArtist")
                        .WithMany("Albums")
                        .HasForeignKey("AlbumArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ArtworkAsset", "Artwork")
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AlbumArtist");

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Artist", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ArtworkAsset", "Artwork")
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Auditorium", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.AuditoriumQueueItem", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Auditorium", "Auditorium")
                        .WithMany("QueueItems")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "QueuedByUser")
                        .WithMany()
                        .HasForeignKey("QueuedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditorium");

                    b.Navigation("QueuedByUser");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AcousticFingerprint", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.TrackFileRevision", "FileRevision")
                        .WithMany()
                        .HasForeignKey("FileRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileRevision");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroup", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroupMember", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.CatalogOverride", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.CatalogRelease", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.LibraryRoot", "LibraryRoot")
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryRoot");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationWorkItem", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", "Job")
                        .WithMany("WorkItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.MetadataProposal", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.OriginalTagSnapshot", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.TrackFileRevision", "FileRevision")
                        .WithMany()
                        .HasForeignKey("FileRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileRevision");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.RecordingCandidate", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationWorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.ReleaseCandidate", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.TrackFileRevision", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.MixedTape", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.MixedTapeItem", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.MixedTape", "MixedTape")
                        .WithMany("Items")
                        .HasForeignKey("MixedTapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixedTape");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.PlaylistItem", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.ScanJob", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.LibraryRoot", "LibraryRoot")
                        .WithMany("ScanJobs")
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryRoot");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Track", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Identification.CatalogRelease", "CatalogRelease")
                        .WithMany()
                        .HasForeignKey("CatalogReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.LibraryRoot", "LibraryRoot")
                        .WithMany("Tracks")
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Artist", "PrimaryArtist")
                        .WithMany("PrimaryTracks")
                        .HasForeignKey("PrimaryArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");

                    b.Navigation("CatalogRelease");

                    b.Navigation("LibraryRoot");

                    b.Navigation("PrimaryArtist");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.TrackArtist", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Artist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.TrackGenre", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Genre", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonaFlyUI.Server.Domain.Entities.Track", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.UserRestriction", b =>
                {
                    b.HasOne("SonaFlyUI.Server.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("PrimaryTracks");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Auditorium", b =>
                {
                    b.Navigation("QueueItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Genre", b =>
                {
                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.AlbumGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Identification.IdentificationJob", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.LibraryRoot", b =>
                {
                    b.Navigation("ScanJobs");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.MixedTape", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SonaFlyUI.Server.Domain.Entities.Track", b =>
                {
                    b.Navigation("PlaylistItems");

                    b.Navigation("TrackArtists");

                    b.Navigation("TrackGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
